services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app

  ngrok:
    image: ngrok/ngrok:latest  # Imagen oficial actualizada
    command: http web:5000
    depends_on:
      - web
    environment:
      - NGROK_AUTHTOKEN=2uiQQ7CMf3AfOtYHx9lW6nF0IaQ_4xchYEupqUMZDyFc72aeY
    ports:
      - "4040:4040"
