services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development

  ngrok:
    image: wernight/ngrok
    depends_on:
      - web
    environment:
      - NGROK_AUTHTOKEN=2uiQQ7CMf3AfOtYHx9lW6nF0IaQ_4xchYEupqUMZDyFc72aeY  # Reemplaza con tu token de ngrok
      - NGROK_PROTOCOL=http
      - NGROK_PORT=web:5000
    ports:
      - "4040:4040"  # Puerto para acceder a la interfaz web de ngrok